<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "lbr_googlemaps"
 *
 * Auto generated by Extension Builder 1970-01-01
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Google Maps',
	'description' => 'Display Location(s) on a google map and edit content of the info-window in the RTE.',
	'category' => 'plugin',
	'author' => 'Marcel Briefs',
	'author_email' => 't3@lbrmedia.net',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 1,
	'version' => '1.0.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.4.0-7.5.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);